### ISSUE TITLE
Scope issue in 0.1.23

### ISSUE THREAD

**Issue by guyaumetremblay** [rigor789/nativescript-vue#70] opened 2017-10-30 01:15 UTC
Hi,

First of all, thanks for all your good work with nativescript-vue!

I got an issue with version 0.1.23 which was not there in 0.1.22. 
I use kazupon plugin vue-i18n to manage the translation. This plugin register a getter to access i18n instance using "this.$i18n".
```
  Object.defineProperty(Vue.prototype, '$i18n', {
    get: function get () { return this._i18n }
  });

...

Vue.prototype.$t = function (key) {
    var values = [], len = arguments.length - 1;
    while ( len-- > 0 ) values[ len ] = arguments[ len + 1 ];

    var i18n = this.$i18n;
    return i18n._t.apply(i18n, [ key, i18n.locale, i18n._getMessages(), this ].concat( values ))
};
``` 

But, with 0.1.23, "this.$i18n" is undefined. 
This example will return "cannot access _t on undefined".

```
import Vue from 'nativescript-vue/dist/index';
import VueI18n from 'vue-i18n';
Vue.use(VueI18n);

let i18n = new VueI18n({
    locale: 'en',
    messages: {
        en: { hello: 'hi there!' }
    }
});

new Vue({
    i18n, 
    template: `<label>{{ $t('hello') }}</label>`
}).$start();
```

Additionnal note: I'm using router-page and vue-router. Don't know if the bug exist without these plugins

**Comment by guyaumetremblay** [comment] 2017-11-15 13:24
Hi @rigor789 , do you have any clue on this?  I hope to be able to update to 1.0.24 (when it will be available) to get the v-view directive.

**Comment by rigor789** [comment] 2017-11-19 23:08
@guyaumetremblay I released `0.1.24` so you should be able to update and use the new directive! I'm also not sure about the issue, would require further investigation!

**Comment by guyaumetremblay** [comment] 2017-11-19 23:23
@rigor789 Thanks for this release. As soon as this bug is fixed, I'll update! 
Hope I can find some time to help on this project...

**Comment by rigor789** [comment] 2017-12-26 18:06
Hey @guyaumetremblay I'm closing this issue because I can't reproduce it on the latest version, here is a working example using i18n (and vuex): https://play.nativescript.org/?template=play-vue&id=OMuAoP

**Closed by rigor789** 2017-12-26 18:06 UTC
Labels: bug
