### ISSUE TITLE
android bug 

### ISSUE THREAD

**Issue by seohangyu** [rigor789/nativescript-vue#95] opened 2017-11-30 10:43 UTC
Turn on Android -> Press Back -> Turn on the app again. What should I do if I get the following error?
 The funny thing is, press the second back button -> re-open the app -> works normally
 How do I fix this bug?
![kakaotalk_2017-11-30-19-43-13_photo_43](https://user-images.githubusercontent.com/23069763/33426884-b785e544-d606-11e7-9883-1eeb7214b467.jpeg)

**Comment by rigor789** [comment] 2017-11-30 11:37
Duplicate of #59

**Closed by rigor789** 2017-11-30 11:37 UTC
