### ISSUE TITLE
css change crash the app

### ISSUE THREAD

**Issue by wighawag** [rigor789/nativescript-vue#89] opened 2017-11-27 11:54 UTC
following the tutorial : https://www.nativescript.org/blog/vue-and-nativescript-in-one-minute

```tns run android```

when I then change the app.css (like font size 32 instead of 18) the app crash and I get :

```
Successfully transferred app.css.
Refreshing application...
System.err: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
System.err:     at android.view.ViewGroup.addViewInner(ViewGroup.java:4313)
System.err:     at android.view.ViewGroup.addView(ViewGroup.java:4149)
System.err:     at android.view.ViewGroup.addView(ViewGroup.java:4090)
System.err:     at android.view.ViewGroup.addView(ViewGroup.java:4063)
System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:985)
System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
System.err:     at android.app.BackStackRecord.run(BackStackRecord.java:803)
System.err:     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
System.err:     at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
System.err:     at android.os.Handler.handleCallback(Handler.java:739)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:148)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5469)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Successfully synced application org.nativescript.vuetest on device ZY2245LW3J.
ActivityManager: Process org.nativescript.vuetest (pid 1076) has died
ActivityManager: cleanUpApplicationRecord -- 1076
```

**Comment by rigor789** [comment] 2017-11-27 13:11
Duplicate of #63

**Closed by rigor789** 2017-11-27 13:11 UTC
Labels: duplicate
